execute pathogen#infect()
syntax on
filetype plugin indent on

nmap \l :setlocal number!<CR>
nmap \o :set paste!<CR>

nmap j gj
nmap k gk

inoremap jk <Esc>
inoremap kj <Esc> 

set incsearch
set ignorecase
set smartcase
set hlsearch
nmap \q :nohlsearch<CR>

